version: "3.9"
services:
  backend:
    build: ./game-app/backend
    container_name: rncp-game-backend
    command: python manage.py runserver
    ports:
      - 8000:8000
    volumes:
      - ./game-app/backend:/backend

  frontend:
    build: ./game-app/frontend
    container_name: rncp-game-frontend
    command: bun run dev
    ports:
      - 5173:5173
    volumes:
      - ./game-app/frontend:/frontend
