import { Inode } from "../types/Inode";
import { type ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}
export const LinuxTerminal: Inode = {
  name: "/",
  type: "folder",
  cwd: "/",

  children: [
    {
      name: "Catman",
      type: "file",
      parent: "/",
      cwd: "/Catman",
      children: [],
      position: [0, 0.5, 0],
      scale: [2, 2, 0],
      imgSrc: "./catman.png",
      isVisible: false,
      isNpc: true,
    },
    {
      name: "home",
      type: "folder",
      parent: "/",
      cwd: "/home",
      imgSrc: "/home.png",
      position: [2, 2.5, 0],
      scale: [2, 2, 0],
      mapSrc: "./home-city.png",
      mapSCale: [15, 8, 0],

      children: [
        {
          name: "OldMan",
          type: "file",
          parent: "/home",
          cwd: "/home/OldMan",
          imgSrc: "./oldman.png",
          children: [],
          position: [0, -2, 0],
          scale: [2, 2, 0],
          isNpc: true,
        },
        {
          name: "OldLady",
          type: "file",
          parent: "/home",
          cwd: "/home/OldLady",
          children: [],
          position: [2, -2, 0],
          scale: [2, 2, 0],
          isNpc: true,
          imgSrc: "./oldlady.png",
        },
        {
          name: "User",
          type: "folder",
          parent: "/home",
          cwd: "/home/User",
          isVisible: false,
          children: [
            {
              name: "Documents",
              type: "folder",
              parent: "/home/user",
              cwd: "/home/User/Documents",
              children: [],
            },
            {
              name: "Downloads",
              type: "folder",
              parent: "/home/User",
              cwd: "/home/User/Downloads",
              children: [],
            },
            {
              name: ".bashrc",
              type: "file",
              parent: "/home/User",
              cwd: "/home/User/.bashrc",
              children: [],
            },
            {
              name: ".ssh",
              type: "folder",
              parent: "/home/User",
              cwd: "/home/User/.ssh",
              children: [],
            },
          ],
        },
      ],
    },
    {
      name: "var",
      type: "folder",
      parent: "/",
      cwd: "/var",
      imgSrc: "/var.png",
      position: [-0.5, 2, 0],
      scale: [1, 1, 0],
      mapSrc: "./var-city.png",
      mapSCale: [15, 8, 0],
      children: [
        {
          name: "Ekko",
          type: "file",
          parent: "/var",
          cwd: "/var/Ekko",
          children: [],
          isNpc: true,
          position: [2.5, -2.5, 0],
          scale: [2, 2, 0],
          imgSrc: "./gecho.png",
        },
        {
          name: "log",
          type: "folder",
          parent: "/var",
          cwd: "/var/log",
          imgSrc: "./log.png",
          scale: [2, 2, 0],
          position: [0, 0, 0],
          children: [
            {
              name: "Syslog",
              type: "file",
              parent: "/var/log",
              cwd: "/var/log/Syslog",
              children: [],
              isNpc: true,
            },
            {
              name: "Authlog",
              type: "file",
              parent: "/var/log",
              cwd: "/var/log/Authlog",
              children: [],
              isNpc: true,
            },
          ],
        },
        {
          name: "www",
          type: "folder",
          parent: "/var",
          cwd: "/var/www",
          imgSrc: "./www.png",
          scale: [3, 3, 0],
          position: [3, 0, 0],
          children: [
            {
              name: "Computer",
              type: "file",
              parent: "/var/www/html",
              cwd: "/var/www/html/Computer",
              children: [],
              isNpc: true,
            },
          ],
        },
      ],
    },
    {
      name: "bin",
      type: "folder",
      parent: "/",
      cwd: "/bin",
      imgSrc: "/bin.png",
      mapSrc: "/bin-city.png",
      position: [5, -1, 0],
      scale: [3, 3, 0],
      children: [
        {
          name: "ClemouilleLaFripouille",
          isNpc: true,
          type: "file",
          parent: "/bin",
          cwd: "/bin/ClemouilleLaFripouille",
          children: [],
        },
        {
          name: "ls",
          type: "file",
          parent: "/bin",
          cwd: "/bin/ls",
          children: [],
          isNpc: true,
        },
        {
          name: "bash",
          type: "file",
          parent: "/bin",
          cwd: "/bin/bash",
          children: [],
          isNpc: true,
        },
      ],
    },
    {
      name: "etc",
      type: "folder",
      parent: "/",
      cwd: "/etc",
      imgSrc: "/etc.png",
      position: [-4, 0, 0],
      scale: [2, 2, 0],
      children: [
        {
          name: "hostname",
          type: "file",
          parent: "/etc",
          cwd: "/etc/hostname",
          children: [],
        },
        {
          name: "hosts",
          type: "file",
          parent: "/etc",
          cwd: "/etc/hosts",
          children: [],
        },
        {
          name: "nginx",
          type: "folder",
          parent: "/etc",
          cwd: "/etc/nginx",
          children: [
            {
              name: "nginx.conf",
              type: "file",
              parent: "/etc/nginx",
              cwd: "/etc/nginx/nginx.conf",
              children: [],
            },
          ],
        },
      ],
    },
    {
      name: "usr",
      type: "folder",
      parent: "/",
      cwd: "/usr",
      imgSrc: "./usr.png",
      position: [-4, 2.5, 0],
      scale: [0.8, 0.8, 0],
      children: [
        {
          name: "bin",
          type: "folder",
          parent: "/usr",
          cwd: "/usr/bin",
          children: [
            {
              name: "python",
              type: "file",
              parent: "/usr/bin",
              cwd: "/usr/bin/python",
              children: [],
            },
            {
              name: "gcc",
              type: "file",
              parent: "/usr/bin",
              cwd: "/usr/bin/gcc",
              children: [],
            },
          ],
        },
        {
          name: "lib",
          type: "folder",
          parent: "/usr",
          cwd: "/usr/lib",
          children: [],
        },
      ],
    },
  ],
};
